# Generated by Django 5.0.4 on 2024-04-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ratings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("rating", models.IntegerField()),
                ("review", models.TextField(blank=True, null=True)),
                ("picture", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recommendations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("reco", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("picture", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=120)),
                ("picture", models.ImageField(blank=True, null=True, upload_to="")),
                ("ratings", models.ManyToManyField(blank=True, to="home.ratings")),
                (
                    "recommendations",
                    models.ManyToManyField(blank=True, to="home.recommendations"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("reco", models.TextField(blank=True, null=True)),
                ("desription", models.TextField(blank=True, null=True)),
                ("picture", models.URLField(blank=True, null=True)),
                ("user", models.ManyToManyField(blank=True, to="home.user")),
            ],
        ),
    ]
