# Generated by Django 5.0.4 on 2024-04-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="password",
            new_name="last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="picture",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ratings",
        ),
        migrations.RemoveField(
            model_name="user",
            name="recommendations",
        ),
        migrations.AddField(
            model_name="ratings",
            name="user",
            field=models.ManyToManyField(blank=True, to="home.user"),
        ),
        migrations.AddField(
            model_name="recommendations",
            name="user",
            field=models.ManyToManyField(blank=True, to="home.user"),
        ),
    ]
