# Generated by Django 5.0.4 on 2024-04-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_name_user_first_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ratings",
            old_name="name",
            new_name="movie",
        ),
        migrations.RenameField(
            model_name="recommendations",
            old_name="name",
            new_name="movie",
        ),
        migrations.RenameField(
            model_name="watchlist",
            old_name="name",
            new_name="movie",
        ),
    ]
