# Generated by Django 5.0.4 on 2024-04-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_name_ratings_movie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendations",
            name="user",
            field=models.ManyToManyField(to="home.user"),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="user",
            field=models.ManyToManyField(to="home.user"),
        ),
    ]
