# Generated by Django 5.0.4 on 2024-04-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_ratings_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratings",
            name="user",
            field=models.ManyToManyField(blank=True, to="home.user"),
        ),
    ]
