# Generated by Django 5.0.4 on 2024-04-24 12:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='regie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('releaseDate', models.DateTimeField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movierating.genre')),
                ('regieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movierating.regie')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='movieID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='movierating.movie'),
            preserve_default=False,
        ),
    ]
