# Generated by Django 5.0.4 on 2024-04-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierating', '0002_author_genre_regie_movie_rating_movieid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='published_date',
        ),
    ]
