# Generated by Django 5.0.4 on 2024-04-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierating', '0003_remove_rating_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='releaseDate',
        ),
    ]
