# Generated by Django 5.0.4 on 2024-04-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierating', '0004_remove_movie_releasedate'),
    ]

    operations = [
    ]
