# Generated by Django 5.0.4 on 2024-04-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierating', '0005_auto_20240424_1427'),
    ]

    operations = [
    ]
