# Generated by Django 5.0.4 on 2024-04-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierating', '0007_auto_20240424_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='movieID',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='userID',
        ),
        migrations.DeleteModel(
            name='movie',
        ),
        migrations.DeleteModel(
            name='rating',
        ),
    ]
