# Generated by Django 5.0.4 on 2024-04-26 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierating', '0010_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='authorID',
        ),
        migrations.RenameModel(
            old_name='author',
            new_name='actor',
        ),
        migrations.CreateModel(
            name='movieActor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ActorsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movierating.actor')),
                ('MovieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movierating.movie')),
            ],
        ),
    ]
